{{- range $job :=  $.Values.jobs }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ printf "%s-%s-%s" (include "backend.fullname" $) $job.name (($.Values | toJson) | sha1sum | trunc 8) }}
  labels:
    app.kubernetes.io/instance: {{ printf "%s-%s" (include "backend.name" $) $job.name }}
    {{- include "backend.labels" $ | nindent 4 }}
spec:
  activeDeadlineSeconds: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "backend.name" $ }}
        app.kubernetes.io/instance: {{ printf "%s-%s" (include "backend.name" $) $job.name }}
    spec:
      {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ printf "%s-%s" (include "backend.name" $) $job.name }}
        image: {{ printf "%s:%s" $.Values.image.repository $.Values.image.tag | quote }}
        imagePullPolicy: {{ $.Values.image.pullPolicy }}
        {{- include "backend.cmd" $job | nindent 8}}
        {{- include "backend.resources" ($job.resources | default ($.Values.resources | default dict)) | nindent 8 }}
        env:
          {{- include "backend.env" (mergeOverwrite dict ($.Values.env | default dict) ($job.env | default dict)) | nindent 10 }}
          {{- include "backend.extraEnv" (concat $.Values.extraEnv ($job.extraEnv | default list)) | nindent 10 }}
        {{- if or .mountConfigMaps .mountSecrets }}
        volumeMounts:
        {{- range .mountConfigMaps }}
        - name: config-{{ .name }}-volume
          mountPath: {{ .mountPath }}
        {{- end }}
        {{- range .mountSecrets }}
        - name: secret-{{ .name }}-volume
          mountPath: {{ .mountPath }}
        {{- end }}
        {{- end }}
      {{- if or .mountConfigMaps .mountSecrets }}
      volumes:
      {{- range .mountConfigMaps }}
      - name: config-{{ .name }}-volume
        configMap:
          name: {{ .name }} 
      {{- end }}
      {{- range .mountSecrets }}
      - name: secret-{{ .name }}-volume
        secret:
          secretName: {{ .name }}
          {{- if .defaultMode }}
          defaultMode: {{ .defaultMode }}
          {{- end }} 
      {{- end }}
      {{ end }}
      restartPolicy: Never
  backoffLimit: {{ .backoffLimit | default 6 }}
{{- end }}
